### ISSUE TITLE
Please include a link to the source code in https://discrete.openmathbooks.org/dmoi4.html

### ISSUE THREAD

**Issue by KamarajuKusumanchi** [oscarlevin/DMOI4#2]
It would be very nice if you can 
* mention that this book is open source and include a link to the source code in https://discrete.openmathbooks.org/dmoi4.html 

thanks
raju

**Comment by KamarajuKusumanchi** [comment]
Also what is the difference between https://github.com/oscarlevin/DMOI4 and https://github.com/oscarlevin/discrete-book ? Am I filing the bugs in the wrong repository?

**Comment by oscarlevin** [comment]
I agree; the 4th edition site needs a lot of work.  Most of this will move content from the 3rd edition's landing page to the "main" 4th edition page.  

The main repository for the book is the `discrete-book` repo; `DMOI4` is sort of a hacky way to make this edition available on Runestone.  I'll put this in the README.
